POST http://localhost:5000/api/sessions
Content-Type: application/json

{
  "userId": "606e14d5b3313e0c24e4ba1c",
  "goalId": 1,
  "title": "test dddd#4 session",
  "startTime": "2020-02-03T20:51:00-05:00"
}