POST http://localhost:5000/api/users
Content-Type: application/json

{
  "id": 1,
  "username": "Vibing",
  "password": "Vibing",
  "adminFlag": false,
  "name": "Vibing",
  "tagline": "Studying is my fave",
  "goals": [
    {
      "id": 30000,
      "title": "Software",
      "totalTasksNum": 2,
      "completedTasksNum": 1,
      "completed": false,
      "completionPercent": 50,
      "tasks": [
        { "id": 0, "task": "Research React", "completed": true },
        { "id": 1, "task": "Make demo app", "completed": false }
      ]
    },
    {
      "id": 4000,
      "title": "React",
      "totalTasksNum": 2,
      "completedTasksNum": 0,
      "completed": false,
      "completionPercent": 0,
      "tasks": [
        { "id": 0, "task": "Research React", "completed": false },
        { "id": 1, "task": "Make demo app", "completed": false }
      ]
    }
  ]
}